// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © marekhanzal

//@version=5
strategy("PiPi v0.6.0", overlay = true, default_qty_value = 2, currency = currency.USD, pyramiding = 1, process_orders_on_close = false, initial_capital = 1000, max_lines_count = 500, max_bars_back = 4900, max_boxes_count = 500, max_labels_count = 500, calc_on_order_fills = false)

//  ====================================================================================================================================================
//      Dependencies
//  ====================================================================================================================================================

import marekhanzal/PiPi2_Context/4  as  ctx
import marekhanzal/PiPi2_Pattern/5  as  pattern
import marekhanzal/PiPi2_Level/2    as  lvl
import marekhanzal/PiPi2_Parser/7   as  parser
import marekhanzal/PiPi2_Toolbox/2  as  toolbox
import marekhanzal/PiPi2_Script/7	as  script
import marekhanzal/PiPi2_Source/10	as  source

//  ====================================================================================================================================================
//      Inputs
//			All the inputs needed by this indicator.
//  ====================================================================================================================================================

const string	        _script_hint		=	"Here you can put your 'pattern' parts of script; there is a limit this input can hold, so use reasonable amount of 'pattern's per input."
var	string		        i_script_0			=	input.text_area("", "- 😎 Init 😎 -",	display = display.none, tooltip = "Here you can put initialization part of the script")
var	string		        i_script_1			=	input.text_area("", "- 😎 Script #1 😎 -",	display = display.none, tooltip = _script_hint)
var	string		        i_script_2			=	input.text_area("", "- 😎 Script #2 😎 -",	display = display.none, tooltip = _script_hint)
var	string		        i_script_3			=	input.text_area("", "- 😎 Script #3 😎 -",	display = display.none,	tooltip = _script_hint)
var	string		        i_script_4			=	input.text_area("", "- 😎 Script #4 😎 -",	display = display.none,	tooltip = _script_hint)

// hack, hehehe
var simple string[]		i_script		=	array.from(i_script_0, i_script_1, i_script_2, i_script_3, i_script_4)

const string	group_plots			=	"- 📈 Plots 📈 -"
var bool		i_day_level			=	input.bool(	false,	"Day Low/High",			group = group_plots, display = display.none,	inline = "day")
var bool		i_day_fibb			=	input.bool(	true,	"Fibbonachi",			group = group_plots, display = display.none,	inline = "day",			tooltip = "Display day's low/high + it's fibbonachi levels")
var bool		i_super_trend_1		=	input.bool(	true,	"Fast SuperTrend",		group = group_plots, display = display.none,	inline = "supertrend",	tooltip = "Show fast SuperTrends")
var bool		i_super_trend_2		=	input.bool(	false,	"Slow SuperTrend",		group = group_plots, display = display.none,	inline = "supertrend",	tooltip = "Show slow SuperTrends")
var bool		i_structures		=	input.bool(	false,	"Structures",			group = group_plots, display = display.none,	inline = "structure")
var bool		i_structure_fibb	=	input.bool(	false,	"Fibbonachi",			group = group_plots, display = display.none,	inline = "structure",	tooltip = "Displays local structure + it's fibbonachi levels, including zones")
var bool		i_ema_1				=	input.bool(	true,	"EMA 1",				group = group_plots, display = display.none,	inline = "ema")
var bool		i_ema_2				=	input.bool(	false,	"EMA 2",				group = group_plots, display = display.none,	inline = "ema")
var bool		i_ema_3				=	input.bool(	false,	"EMA 3",				group = group_plots, display = display.none,	inline = "ema")
var bool		i_cci_exits         =	input.bool(	true,	"CCI Signal",           group = group_plots, display = display.none)

//  ====================================================================================================================================================
//      Types specific for this system
//  ====================================================================================================================================================

//	@type				This is a result from the main indicator fucntion
//	@field	contexts	All the contexts produced by the indicator
type Result
	ctx.Contexts    contexts

//  ---     Factory methods

result_create() =>
    Result.new(ctx.contexts_create())

//  ====================================================================================================================================================
//      Main Entry
//			This is main entry point of this system; all the indicators, workflow, script parsing and so on are here.
//  ====================================================================================================================================================

//	@function	Main entry point of this indicator; even without any plotting, it could be used for strategy testing using TradingView built-in tester
main(string[] script) =>
	var Result          _result     =	result_create()
    ctx.Contexts        _contexts   =   _result.contexts
	var script.Script   _script		=	parser.parse(script)

	if toolbox.use_init()
        source.use_defaults     	(_contexts)
		script.eval_init			(_contexts, _script)

	//	---	Individual providers (sources); if you want to add your own indicator/provider/whatever, put it here

	//	Candle "must" be first as others may want to access values it provides (candle has no Dependencies)
	source.use_candle           	(_contexts)
    source.use_day              	(_contexts)
    source.use_day_fibbonachi   	(_contexts)
    source.use_ema              	(_contexts)
    source.use_cci              	(_contexts)
	source.use_session          	(_contexts)
	source.use_volume				(_contexts)
	source.use_macd2				(_contexts)
	source.use_structure			(_contexts)
	source.use_structure_fibbonachi	(_contexts)
	source.use_super_trend			(_contexts)
	//	Candle levels "must" be last, because providers may export levels which candle handles (computes flags against those levels)
	source.use_candle_levels    	(_contexts)

	//	---	That's it, there is nothing else interesting; if you are searching for the magick executing all actions and so on,
	//		Look into script as it handles pattern matching, action execution and all the other cool stuff

	script.eval						(_contexts, _script)

	//	Trader must be last one as it handles Strategy Tester and order stuff (potentially) produced by a script
	source.use_trader				(_contexts)

	_result

//  ====================================================================================================================================================
//      Main Entry execution
//  ====================================================================================================================================================

_result		=	main(i_script)
_contexts	=	_result.contexts

_fibb_alpha_1_linw			=	75
_fibb_alpha_1_background	=	92.5
_fibb_alpha_2_line			=	85
_fibb_alpha_2_background	=	95

//  ====================================================================================================================================================
//      Render day's low and high
//  ====================================================================================================================================================

plot(i_day_level ? ctx.contexts_get_level(_contexts, "day", "level").high	:	na,	"Day High",	style =	plot.style_steplinebr,	linewidth = 2,	display = display.pane, color = color.teal)
plot(i_day_level ? ctx.contexts_get_level(_contexts, "day", "level").low	:	na,	"Day Low",	style =	plot.style_steplinebr,	linewidth = 2,	display = display.pane, color = color.fuchsia)

//  ====================================================================================================================================================
//      Render Fibbonachi levels
//  ====================================================================================================================================================

_no_fill		=	ctx.contexts_get_bool(_contexts, "day", "change", false)

_color_0		=	color.new(color.red, _fibb_alpha_1_background)
_plot_0_1 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "0").low	:	na,		"Fibb - 0 (low)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_0, _fibb_alpha_1_linw), 		display = display.pane)
_plot_0_2 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "0").high	:	na,		"Fibb - 0 (high)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_0, _fibb_alpha_1_linw),		display = display.pane)
fill(_plot_0_1, _plot_0_2, _no_fill ? na : _color_0,	"Fibb - 0 (fill)")

_color_20		=	color.new(color.yellow, _fibb_alpha_1_background)
_plot_20_1 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "20").low	:	na,		"Fibb - 23.6 (low)", 	linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_20, _fibb_alpha_1_linw), 	display = display.pane)
_plot_20_2 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "20").high	:	na,		"Fibb - 23.6 (high)",	linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_20, _fibb_alpha_1_linw),		display = display.pane)
fill(_plot_20_1, _plot_20_2, _no_fill ? na : _color_20,	"Fibb - 23.6 (fill)")

_color_30		=	color.new(color.orange, _fibb_alpha_2_background)
_plot_30_1 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "30").low	:	na,		"Fibb - 38.2 (low)",	linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_30, _fibb_alpha_2_line),		display = display.pane)
_plot_30_2 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "30").high	:	na,		"Fibb - 38.2 (high)",	linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_30, _fibb_alpha_2_line),		display = display.pane)
fill(_plot_30_1, _plot_30_2, _no_fill ? na : _color_30,	"Fibb - 38.2 (fill)")

_color_50		=	color.new(color.green, _fibb_alpha_1_background)
_plot_50_1 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "50").low	:	na,		"Fibb - 50 (low)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_50, _fibb_alpha_1_linw),		display = display.pane)
_plot_50_2 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "50").high	:	na,		"Fibb - 50 (high)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_50, _fibb_alpha_1_linw), 	display = display.pane)
fill(_plot_50_1, _plot_50_2, _no_fill ? na : _color_50,	"Fibb - 50 (fill)")

_color_60		=	color.new(color.teal, _fibb_alpha_2_background)
_plot_60_1 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "60").low	:	na,		"Fibb - 61.8 (low)",	linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_60, _fibb_alpha_2_line), 	display = display.pane)
_plot_60_2 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "60").high	:	na,		"Fibb - 61.8 (high)",	linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_60, _fibb_alpha_2_line), 	display = display.pane)
fill(_plot_60_1, _plot_60_2, _no_fill ? na : _color_60,	"Fibb - 61.8 (fill)")

_color_70		=	color.new(color.aqua, _fibb_alpha_1_background)
_plot_70_1 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "70").low	:	na,		"Fibb - 78.6 (low)",	linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_70, _fibb_alpha_1_linw),		display = display.pane)
_plot_70_2 		=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "70").high	:	na,		"Fibb - 78.6 (high)",	linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_70, _fibb_alpha_1_linw), 	display = display.pane)
fill(_plot_70_1, _plot_70_2, _no_fill ? na : _color_70,	"Fibb - 78.6 (fill)")

_color_100		=	color.new(color.green, _fibb_alpha_1_background)
_plot_100_1 	=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "100").low	:	na,		"Fibb - 100 (low)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_100, _fibb_alpha_1_linw),	display = display.pane)
_plot_100_2 	=	plot(i_day_fibb ?	ctx.contexts_get_level(_contexts, "day-fibbonachi", "100").high	:	na,		"Fibb - 100 (high)",	linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_100, _fibb_alpha_1_linw),	display = display.pane)
fill(_plot_100_1, _plot_100_2, _no_fill ? na : _color_100,	"Fibb - 100 (fill)")

//  ====================================================================================================================================================
//      Render Local Structure
//  ====================================================================================================================================================

plot(i_structures	?	ctx.contexts_get_level(_contexts, "structure", "low").level	:	na,		"Structure low",	style = plot.style_line, linewidth = 3, 	color = color.new(color.fuchsia,	60),	display = display.pane)
plot(i_structures	?	ctx.contexts_get_level(_contexts, "structure", "high").level	:	na,		"Structure high",	style = plot.style_line, linewidth = 3, 	color = color.new(color.teal,		60),	display = display.pane)

//  ====================================================================================================================================================
//      Local Structure Fibbonachi
//  ====================================================================================================================================================

_color_00		=	color.new(color.red, _fibb_alpha_1_background)
_plot_00_1 		=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "0").low	:	na,			"Structure Fibb - 0 (low)",			linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_00, _fibb_alpha_1_linw), 		display = display.pane)
_plot_00_2 		=	plot(i_structure_fibb ?	ctx.contexts_get_level(_contexts, "structure-fibbonachi", "0").high	:	na,			"Structure Fibb - 0 (high)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_00, _fibb_alpha_1_linw),		display = display.pane)
fill(_plot_00_1, _plot_00_2,	_color_00,		"Structure Fibb - 0 (fill)")

_color_020		=	color.new(color.yellow, _fibb_alpha_1_background)
_plot_020_1 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "20").low		:	na,		"Structure Fibb - 23.6 (low)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_020, _fibb_alpha_1_linw), 	display = display.pane)
_plot_020_2 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "20").high	:	na,		"Structure Fibb - 23.6 (high)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_020, _fibb_alpha_1_linw),		display = display.pane)
fill(_plot_020_1, _plot_020_2,	_color_020,		"Structure Fibb - 23.6 (fill)")

_color_030		=	color.new(color.orange, _fibb_alpha_2_background)
_plot_030_1 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "30").low		:	na,		"Structure Fibb - 38.2 (low)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_30, _fibb_alpha_2_line),		display = display.pane)
_plot_030_2 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "30").high	:	na,		"Structure Fibb - 38.2 (high)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_30, _fibb_alpha_2_line),		display = display.pane)
fill(_plot_030_1, _plot_030_2,	_color_030,		"Structure Fibb - 38.2 (fill)")

_color_050		=	color.new(color.green, _fibb_alpha_1_background)
_plot_050_1 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "50").low		:	na,		"Structure Fibb - 50 (low)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_50, _fibb_alpha_1_linw),		display = display.pane)
_plot_050_2 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "50").high	:	na,		"Structure Fibb - 50 (high)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_50, _fibb_alpha_1_linw), 	display = display.pane)
fill(_plot_050_1, _plot_050_2,  _color_050,		"Structure Fibb - 50 (fill)")

_color_060		=	color.new(color.teal, _fibb_alpha_2_background)
_plot_060_1 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "60").low		:	na,		"Structure Fibb - 61.8 (low)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_60, _fibb_alpha_2_line), 	display = display.pane)
_plot_060_2 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "60").high	:	na,		"Structure Fibb - 61.8 (high)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_60, _fibb_alpha_2_line), 	display = display.pane)
fill(_plot_060_1, _plot_060_2,	_color_060,		"Structure Fibb - 61.8 (fill)")

_color_070		=	color.new(color.aqua, _fibb_alpha_1_background)
_plot_070_1 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "70").low		:	na,		"Structure Fibb - 78.6 (low)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_70, _fibb_alpha_1_linw),		display = display.pane)
_plot_070_2 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "70").high	:	na,		"Structure Fibb - 78.6 (high)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_70, _fibb_alpha_1_linw), 	display = display.pane)
fill(_plot_070_1, _plot_070_2,  _color_070,		"Structure Fibb - 78.6 (fill)")

_color_0100		=	color.new(color.green, _fibb_alpha_1_background)
_plot_0100_1 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "100").low	:	na,		"Structure Fibb - 100 (low)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_100, _fibb_alpha_1_linw),	display = display.pane)
_plot_0100_2 	=	plot(i_structure_fibb ? ctx.contexts_get_level(_contexts, "structure-fibbonachi", "100").high	:	na,		"Structure Fibb - 100 (high)",		linewidth = 1, style = plot.style_steplinebr, color = color.new(_color_100, _fibb_alpha_1_linw),	display = display.pane)
fill(_plot_0100_1, _plot_0100_2, _color_0100,	"Structure Fibb - 100 (fill)")

//  ====================================================================================================================================================
//      Render Profit/Loss for trades
//  ====================================================================================================================================================

_profit_long	=	plot(ctx.contexts_get_bool(_contexts, "trade", "long") ? ctx.contexts_get_float(_contexts, "trade", "profit")	:	na,		"Long Profit",	offset = 1,	style = plot.style_steplinebr, linewidth = 2, color = color.new(color.green, 50),	display = display.pane)
_loss_long		=	plot(ctx.contexts_get_bool(_contexts, "trade", "long") ? ctx.contexts_get_float(_contexts, "trade", "loss") 	:	na,		"Long Loss",	offset = 1,	style = plot.style_steplinebr, linewidth = 2, color = color.new(color.red, 50),	display = display.pane)
fill(_profit_long, _loss_long, title = "Long Background", color = color.new(color.green, 95))

_profit_short	=	plot(ctx.contexts_get_bool(_contexts, "trade", "short") ? ctx.contexts_get_float(_contexts, "trade", "profit")	:	na,		"Short Profit",	offset = 1,	style = plot.style_steplinebr, linewidth = 2, color = color.new(color.green, 50),	display = display.pane)
_loss_short		=	plot(ctx.contexts_get_bool(_contexts, "trade", "short") ? ctx.contexts_get_float(_contexts, "trade", "loss") 	:	na,		"Short Loss",	offset = 1,	style = plot.style_steplinebr, linewidth = 2, color = color.new(color.red, 50),	display = display.pane)
fill(_profit_short, _loss_short, title = "Short Background", color = color.new(color.red, 95))

//  ====================================================================================================================================================
//      Render SuperTrend
//  ====================================================================================================================================================

plot(i_super_trend_1 and	ctx.contexts_get_bool(_contexts, "super-trend", "fast.up")		?	ctx.contexts_get_float(_contexts, "super-trend", "fast.signal") : na, "SuperTrend - Fast Uptrend",		linewidth = 3,	style = plot.style_linebr,	color = color.new(color.aqua, 15),		display = display.pane)
plot(i_super_trend_1 and	ctx.contexts_get_bool(_contexts, "super-trend", "fast.down")	?	ctx.contexts_get_float(_contexts, "super-trend", "fast.signal") : na, "SuperTrend - Fast Downtrend",	linewidth = 3,	style = plot.style_linebr,	color = color.new(color.purple, 15),	display = display.pane)

plot(i_super_trend_2 and	ctx.contexts_get_bool(_contexts, "super-trend", "slow.up")		?	ctx.contexts_get_float(_contexts, "super-trend", "slow.signal") : na, "SuperTrend - Slow Uptrend",		linewidth = 4,	style = plot.style_linebr,	color = color.new(color.aqua, 30),		display = display.pane)
plot(i_super_trend_2 and	ctx.contexts_get_bool(_contexts, "super-trend", "slow.down")	?	ctx.contexts_get_float(_contexts, "super-trend", "slow.signal") : na, "SuperTrend - Slow Downtrend",	linewidth = 4,	style = plot.style_linebr,	color = color.new(color.purple, 30),	display = display.pane)

//  ====================================================================================================================================================
//      Render Trade flags
//  ====================================================================================================================================================

plotshape(ctx.contexts_get_bool(_contexts, "ctx", "buy"),		"Buy Label",		style = shape.labelup,		location = location.belowbar, color = color.teal,       display = display.pane)
plotshape(ctx.contexts_get_bool(_contexts, "ctx", "sell"),		"Sell Label",		style = shape.labeldown,	location = location.abovebar, color = color.fuchsia,    display = display.pane)
plotshape(ctx.contexts_get_bool(_contexts, "trade", "closed"),	"Closed",			style = shape.xcross,		location = location.abovebar, color = color.red,        display = display.pane)

//  ====================================================================================================================================================
//      Session
//  ====================================================================================================================================================

bgcolor(ctx.contexts_get_bool(_contexts, "session", "open") ? na :color.new(color.gray, 95), title = "Out-of-Session Background")

//  ====================================================================================================================================================
//      Render EMA
//  ====================================================================================================================================================

plot(i_ema_1 ? ctx.contexts_get_level(_contexts, "ema", "1").level : na, "EMA-1", color = color.blue,       display = display.pane)
plot(i_ema_2 ? ctx.contexts_get_level(_contexts, "ema", "2").level : na, "EMA-2", color = color.orange,     display = display.pane)
plot(i_ema_3 ? ctx.contexts_get_level(_contexts, "ema", "3").level : na, "EMA-3", color = color.purple,     display = display.pane)

//  ====================================================================================================================================================
//      CCI markers
//  ====================================================================================================================================================

plotshape(i_cci_exits and ctx.contexts_get_bool(_contexts, "cci", "below.exit"),		"CCI Below - Exit",		    style = shape.circle,		size = size.tiny,  location = location.bottom, color = color.teal,         display = display.pane)
plotshape(i_cci_exits and ctx.contexts_get_bool(_contexts, "cci", "above.exit"),		"CCI Above - Exit",		    style = shape.circle,		size = size.tiny,  location = location.bottom, color = color.fuchsia,      display = display.pane)

plotshape(i_cci_exits and ctx.contexts_get_bool(_contexts, "cci", "below.enter"),		"CCI Below - Enter",		style = shape.xcross,      	size = size.tiny,  location = location.bottom, color = color.teal,         display = display.pane)
plotshape(i_cci_exits and ctx.contexts_get_bool(_contexts, "cci", "above.enter"),		"CCI Above - Enter",		style = shape.xcross,		size = size.tiny,  location = location.bottom, color = color.fuchsia,      display = display.pane)
